# Default values for admission-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: admission-webhook-server
namespace: admission-webhooks
image: admission-controller-webapi:latest
path: /mutate
ca_pem_b64: inserted-at-deploy-time
imagePullSecret: regcred

tls:
  crt: inserted-at-deploy-time
  key: inserted-at-deploy-time

operations:
- "CREATE"
- "UPDATE"
- "DELETE"

resources:
- "pods"
- "ingress"

